---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: data_bags
    driver:
     network:
      - ["private_network", {ip: "192.168.17.19"}]
    run_list:
     - recipe[apt::default]
     - recipe[test-rundeck-api::default]
    attributes:
