name             'test-rundeck-api'
maintainer       'Daniel Klopp'
maintainer_email 'dsklopp@gmail.com'
license          'All rights reserved'
description      'Installs/Configures test-rundeck-api'
long_description 'Installs/Configures test-rundeck-api'
version          '0.1.0'

depends 'apt'
depends 'rundeck'
